# Generated by Django 4.0.6 on 2022-08-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tradeinfo_delete_book_delete_grocery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeinfo',
            old_name='name',
            new_name='Name',
        ),
    ]
